image: 253882794486.dkr.ecr.us-east-1.amazonaws.com/build-tools:864d3610-node-18

stages:
  - test



before_script:
    - apt-get update && apt-get install --yes libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - npm ci
    - npm run cy:clear


api-test:
  stage: test
  when: always
  only: 
    - develop
  script:  
    - npm run cy:run:nonprod 
  artifacts:
    expire_in: 30 days
    when: always
    paths:
      - reports


api-test-report:
  stage: test
  when: always
  only:
    - master
  script:  
    - npm run cy:dash:nonprod
