include:
  - project: 'fca/architecture/IaC/cloud-digital/common-ci'
    file: 'job-commons.yml'

stages:
  - test
  - build


.cypress_job:
  stage: test
  image: cypress/base:16.13.0
  when: manual
  script:
    - npm ci
    - $(npm bin)/cypress run --env nonprod=nonprod --spec $TEST_FILE

api-test-buyers:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/buyers/*.cy.ts


api-test-bff:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/bff/*.cy.ts

api-test-enterprises:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/enterprises/*.cy.ts


api-test-integrations:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/integrations/*.cy.ts



api-test-investors:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/investors/*.cy.ts


api-test-operations:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/operations/*.cy.ts


api-test-sponsors:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/sponsors/*.cy.ts


api-test-suppliers:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/suppliers/*.cy.ts

api-test-users:
  extends:
    - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/users/*.cy.ts

api-test-all:
  extends:
  - .cypress_job
  variables:
    TEST_FILE: cypress/e2e/api/*/*.cy.ts


api-test:
  stage: test
  only:
    - master
  script:  
     - npm ci
     - $(npm bin)/cypress run --env nonprod=nonprod 
  artifacts:
    expire_in: 30 days
    when: always
    paths:
      - reports


api-test-report:
  stage: test
  only:
    - master
  when: manual
  script:  
     - npm ci
     - $(npm bin)/cypress run --env nonprod=nonprod 

