image: cypress/base:12 #253882794486.dkr.ecr.us-east-1.amazonaws.com/build-tools:864d3610-node-18

#include:
#  - project: 'fca/architecture/IaC/cloud-digital/common-ci'
#    file: 'job-commons.yml'

stages:
  - test



e2e:
  stage: test
  only:
    - develop
    - master
  script:  
    - npm run cy:run:nonprod #npx currents run --env homolog=homolog --parallel --record --key H9ImBxO47DkUGCxF --ci-build-id results-e2e-${CI_COMMIT_SHA:0:8}

